import ports from "../data/ports.json";

// Standard load/discharge port suggestions (v1.2, design_problem.md PT-18 follow-up). `ports.json` is generated by
// `scripts/build_port_list.py` from the UN/LOCODE seaport list, with a small set of aliases baked in for ports the
// client trades under an old spelling (see that script's ALIASES). Free text is always accepted — this only powers
// suggestions, never a hard restriction (client decision, 2026-09-22).

interface PortEntry {
  locode: string;
  name: string;
  aliases?: string[];
}

const STANDARD_PORTS = ports as PortEntry[];
const RESULT_LIMIT = 20;

export function searchCargoPorts(query: string, customPorts: readonly string[]): string[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  const results: string[] = [];
  for (const port of STANDARD_PORTS) {
    if (port.name.toLowerCase().includes(q) || port.aliases?.some((a) => a.toLowerCase().includes(q))) {
      results.push(port.name);
      if (results.length >= RESULT_LIMIT) return results;
    }
  }
  for (const name of customPorts) {
    if (name.toLowerCase().includes(q)) {
      results.push(name);
      if (results.length >= RESULT_LIMIT) return results;
    }
  }
  return results;
}
