// Step sizes of the up / down arrows, taken from the predecessor's _INPUT_CATEGORIES (app_streamlit.py), where the
// client already worked with them.
export const FIELD_STEPS: Record<string, number> = {
  quantity: 100,
  freight_rate: 0.5,
  commission_rate: 1.25,
  loading_days: 0.5,
  discharging_days: 0.5,
  margin_days: 0.5,
  ballast_distance: 10,
  laden_distance: 10,
  cjk_laden_nm: 10,
  cjk_laden_mgo_consumption: 0.1,
  cjk_ballast_nm: 10,
  cjk_ballast_mgo_consumption: 0.1,
  qz_laden_nm: 10,
  qz_laden_mgo_consumption: 0.1,
  qz_ballast_nm: 10,
  qz_ballast_mgo_consumption: 0.1,
  ballast_speed: 0.5,
  laden_speed: 0.5,
  hfo_price: 50,
  mgo_price: 50,
  hfo_laden_consumption: 0.1,
  mgo_laden_consumption: 0.05,
  hfo_ballast_consumption: 0.1,
  mgo_ballast_consumption: 0.05,
  hfo_port_consumption: 0.1,
  mgo_port_consumption: 0.05,
  load_port_pda: 500,
  discharge_port_pda: 500,
  loading_rate: 100,
  discharging_rate: 100,
  loading_cost: 500,
  discharging_cost: 500,
  lashing_cost: 100,
  cev_cost: 100,
  ilohc_cost: 100,
  shipowner_asking_tce: 100,
  market_benchmark: 100,
  go_threshold_pct: 0.1,
};

export const TOTAL_FREIGHT_STEP = 1000;
export const OTHER_COST_STEP = 100;
